import type { ClaudeInstance, TerminalLine } from './types';

const createTerminalHistory = (lines: Partial<TerminalLine>[]): TerminalLine[] => {
  return lines.map((line, i) => ({
    id: `line-${i}`,
    type: line.type || 'output',
    content: line.content || '',
    timestamp: new Date(Date.now() - (lines.length - i) * 60000),
  }));
};

export const mockInstances: ClaudeInstance[] = [
  {
    id: 'inst-1',
    name: 'ui agent',
    model: 'Opus 4.5',
    status: 'idle',
    project: 'openui',
    branch: 'main',
    workingDirectory: '/Users/dev/projects/openui',
    currentTask: 'Waiting for instruction',
    metrics: {
      contextUsage: 12,
      cost: 0.1352,
      linesAdded: 0,
      linesRemoved: 0,
      tokensIn: 7213,
      tokensOut: 568,
    },
    terminalHistory: createTerminalHistory([
      { type: 'system', content: '● Session started' },
      { type: 'output', content: 'Let me look for actual source files in the project, not node_modules.' },
      { type: 'input', content: '→ Search (pattern: "client/src/**/*.ts")' },
      { type: 'output', content: '  Found 2 files (ctrl+e to expand)' },
      { type: 'input', content: '→ Read (client/src/stores/useStore.ts)' },
      { type: 'output', content: '  Read 131 lines' },
      { type: 'output', content: "Here's a haiku inspired by useStore.ts - a state management" },
      { type: 'output', content: 'file for an agent-based UI:' },
      { type: 'output', content: '' },
      { type: 'output', content: '  Agents come and go' },
      { type: 'output', content: '  Sessions flow through canvas nodes' },
      { type: 'output', content: '  State maps hold them all.' },
      { type: 'output', content: '' },
      { type: 'input', content: '→ Write it to a file called haiku.txt' },
      { type: 'system', content: 'Opus 4.5 | openui | +0 -0 | ctx:12K | $0.1352 |' },
      { type: 'system', content: '[OUTPUT:{"m":"Opus 4.5","n":0.1352,"in":0,"i":idle"}]' },
    ]),
    startedAt: new Date(Date.now() - 3600000),
    lastActivityAt: new Date(Date.now() - 120000),
  },
  {
    id: 'inst-2',
    name: 'Claude Code 2',
    model: 'Sonnet 4',
    status: 'disconnected',
    project: 'openui',
    branch: 'main',
    workingDirectory: '/Users/dev/projects/openui',
    metrics: {
      contextUsage: 0,
      cost: 0,
      linesAdded: 0,
      linesRemoved: 0,
      tokensIn: 0,
      tokensOut: 0,
    },
    terminalHistory: [],
    startedAt: new Date(Date.now() - 7200000),
    lastActivityAt: new Date(Date.now() - 3600000),
  },
  {
    id: 'inst-3',
    name: 'Claude Code 3',
    model: 'Sonnet 4',
    status: 'disconnected',
    project: 'openui',
    branch: 'main',
    workingDirectory: '/Users/dev/projects/openui',
    metrics: {
      contextUsage: 0,
      cost: 0,
      linesAdded: 0,
      linesRemoved: 0,
      tokensIn: 0,
      tokensOut: 0,
    },
    terminalHistory: [],
    startedAt: new Date(Date.now() - 7200000),
    lastActivityAt: new Date(Date.now() - 3600000),
  },
  {
    id: 'inst-4',
    name: 'Claude Code 4',
    model: 'Sonnet 4',
    status: 'offline',
    project: 'openui',
    branch: 'main',
    workingDirectory: '/Users/dev/projects/openui',
    metrics: {
      contextUsage: 0,
      cost: 0,
      linesAdded: 0,
      linesRemoved: 0,
      tokensIn: 0,
      tokensOut: 0,
    },
    terminalHistory: [],
    startedAt: new Date(Date.now() - 7200000),
    lastActivityAt: new Date(Date.now() - 3600000),
  },
  {
    id: 'inst-5',
    name: 'api-refactor',
    model: 'Opus 4.5',
    status: 'working',
    project: 'backend-api',
    branch: 'feature/auth-v2',
    workingDirectory: '/Users/dev/projects/backend-api',
    currentTask: 'Implementing OAuth2 flow',
    metrics: {
      contextUsage: 45,
      cost: 0.4821,
      linesAdded: 234,
      linesRemoved: 89,
      tokensIn: 23456,
      tokensOut: 4521,
    },
    terminalHistory: createTerminalHistory([
      { type: 'system', content: '● Session started' },
      { type: 'output', content: 'Starting OAuth2 implementation...' },
      { type: 'input', content: '→ Read (src/auth/oauth.ts)' },
      { type: 'output', content: '  Read 245 lines' },
      { type: 'output', content: 'I see the current OAuth implementation. Let me refactor this to support the new token flow.' },
      { type: 'input', content: '→ Edit (src/auth/oauth.ts)' },
      { type: 'output', content: '  Modified 45 lines' },
      { type: 'input', content: '→ Write (src/auth/tokenManager.ts)' },
      { type: 'output', content: '  Created new file with 120 lines' },
      { type: 'output', content: 'Now implementing the refresh token logic...' },
    ]),
    startedAt: new Date(Date.now() - 1800000),
    lastActivityAt: new Date(Date.now() - 30000),
  },
  {
    id: 'inst-6',
    name: 'test-runner',
    model: 'Haiku 3.5',
    status: 'waiting_input',
    project: 'backend-api',
    branch: 'main',
    workingDirectory: '/Users/dev/projects/backend-api',
    currentTask: 'Waiting for test configuration',
    metrics: {
      contextUsage: 8,
      cost: 0.0234,
      linesAdded: 0,
      linesRemoved: 0,
      tokensIn: 2341,
      tokensOut: 234,
    },
    terminalHistory: createTerminalHistory([
      { type: 'system', content: '● Session started' },
      { type: 'output', content: 'Ready to run tests. Which test suite would you like me to execute?' },
      { type: 'system', content: '⚠ Waiting for input...' },
    ]),
    startedAt: new Date(Date.now() - 600000),
    lastActivityAt: new Date(Date.now() - 300000),
  },
  {
    id: 'inst-7',
    name: 'docs-writer',
    model: 'Sonnet 4',
    status: 'online',
    project: 'company-docs',
    branch: 'docs/api-reference',
    workingDirectory: '/Users/dev/projects/company-docs',
    currentTask: 'Writing API documentation',
    metrics: {
      contextUsage: 28,
      cost: 0.1567,
      linesAdded: 456,
      linesRemoved: 12,
      tokensIn: 12345,
      tokensOut: 3456,
    },
    terminalHistory: createTerminalHistory([
      { type: 'system', content: '● Session started' },
      { type: 'output', content: 'Generating API documentation for the authentication endpoints.' },
      { type: 'input', content: '→ Read (src/routes/auth/*.ts)' },
      { type: 'output', content: '  Read 8 files, 1,245 lines total' },
      { type: 'input', content: '→ Write (docs/api/authentication.md)' },
      { type: 'output', content: '  Created documentation with 234 lines' },
      { type: 'output', content: 'Documentation complete. Moving to user endpoints...' },
    ]),
    startedAt: new Date(Date.now() - 2400000),
    lastActivityAt: new Date(Date.now() - 60000),
  },
];
